apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80       # Port on the Service
      targetPort: 8080 # Port on the Pods
  type: NodePort
